### PR TITLE
Append newline to log if not present

### PR DESCRIPTION
**Pull request by jsumners**
Resolves comment https://github.com/dusted-go/logging/pull/4#pullrequestreview-2039736198

### CODE REVIEW

**Comment by dustinmoris** [comment]
Thanks for providing a fix so promptly. I'm wondering if we even need the `HasSuffix` check. Shouldn't this logger always end a log entry with a new line as it's sole intention is to be used as a console logger?

**Comment by jsumners** [comment]
Yeah, I supposed I was trying to account for a scenario that is not possible. I have revised it to always append a newline character.

**Review by dustinmoris — APPROVED** [review]
LGTM

**Comment by dustinmoris** [comment]
Many thanks 🙏

**Pull request merged**
